"""initial_schema

Revision ID: 2f969c1594d2
Revises: 
Create Date: 2026-03-28 16:54:39.252767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f969c1594d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_monthly_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_month', sa.String(length=7), nullable=False),
    sa.Column('final_ranking', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('total_unique_voters', sa.Integer(), nullable=False),
    sa.Column('top_clip_id', sa.Integer(), nullable=True),
    sa.Column('top_clip_score', sa.Float(), nullable=True),
    sa.Column('month_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_month', name='uq_leaderboard_monthly_summary_month')
    )
    op.create_index(op.f('ix_leaderboard_monthly_summary_id'), 'leaderboard_monthly_summary', ['id'], unique=False)
    op.create_index('ix_leaderboard_monthly_summary_month', 'leaderboard_monthly_summary', ['snapshot_month'], unique=False)
    op.create_index(op.f('ix_leaderboard_monthly_summary_snapshot_month'), 'leaderboard_monthly_summary', ['snapshot_month'], unique=True)
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_month', sa.String(length=7), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ranking', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_snapshots_id'), 'leaderboard_snapshots', ['id'], unique=False)
    op.create_index('ix_leaderboard_snapshots_month', 'leaderboard_snapshots', ['snapshot_month'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_snapshot_month'), 'leaderboard_snapshots', ['snapshot_month'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_snapshot_timestamp'), 'leaderboard_snapshots', ['snapshot_timestamp'], unique=False)
    op.create_index('ix_leaderboard_snapshots_timestamp', 'leaderboard_snapshots', ['snapshot_timestamp'], unique=False)
    op.create_table('clip_video_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clip_video_cache_clip_id'), 'clip_video_cache', ['clip_id'], unique=True)
    op.create_index(op.f('ix_clip_video_cache_id'), 'clip_video_cache', ['id'], unique=False)
    # Drop in FK-safe order: vote → clip → user_streamer
    op.drop_index(op.f('ix_vote_id'), table_name='vote')
    op.drop_table('vote')
    op.drop_index(op.f('ix_clip_id'), table_name='clip')
    op.drop_index(op.f('ix_clip_month_key'), table_name='clip')
    op.drop_table('clip')
    op.drop_index(op.f('ix_user_streamer_id'), table_name='user_streamer')
    op.drop_table('user_streamer')
    op.alter_column('clips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('clips', 'score')
    op.add_column('user_clip_history', sa.Column('clip_description', sa.String(), nullable=True))
    op.add_column('user_clip_history', sa.Column('clip_tags', sa.Text(), nullable=True))
    op.add_column('user_clip_history', sa.Column('edited_title', sa.String(), nullable=True))
    op.add_column('user_clip_history', sa.Column('chat_messages', sa.Text(), nullable=True))
    op.add_column('user_clip_history', sa.Column('edit_history', sa.Text(), nullable=True))
    op.add_column('user_clip_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_clip_history', sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_clip_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_user_clip_history_id'), 'user_clip_history', ['id'], unique=False)
    op.alter_column('user_streamers', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # Remove orphaned rows that have no matching user before adding FK constraint
    op.execute("DELETE FROM user_streamers WHERE user_id NOT IN (SELECT id FROM users)")
    op.create_foreign_key(None, 'user_streamers', 'users', ['user_id'], ['id'])
    # Enum cast requires USING clause in PostgreSQL; type may already exist from prior runs
    op.execute("DO $$ BEGIN CREATE TYPE userrole AS ENUM ('USER', 'PRO', 'ADMIN'); EXCEPTION WHEN duplicate_object THEN NULL; END $$")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint('unique_vote', 'votes', ['user_id', 'clip_id'])
    # Remove orphaned votes before adding FK constraints
    op.execute("DELETE FROM votes WHERE user_id NOT IN (SELECT id FROM users)")
    op.execute("DELETE FROM votes WHERE clip_id NOT IN (SELECT id FROM clips)")
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint('unique_vote', 'votes', type_='unique')
    op.alter_column('votes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR USING role::VARCHAR")
    op.execute("DROP TYPE IF EXISTS userrole")
    op.drop_constraint(None, 'user_streamers', type_='foreignkey')
    op.alter_column('user_streamers', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_clip_history_id'), table_name='user_clip_history')
    op.alter_column('user_clip_history', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('user_clip_history', 'last_edited_at')
    op.drop_column('user_clip_history', 'updated_at')
    op.drop_column('user_clip_history', 'edit_history')
    op.drop_column('user_clip_history', 'chat_messages')
    op.drop_column('user_clip_history', 'edited_title')
    op.drop_column('user_clip_history', 'clip_tags')
    op.drop_column('user_clip_history', 'clip_description')
    op.add_column('clips', sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('clips', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('vote',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vote_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clip_id'], ['clip.id'], name=op.f('vote_clip_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vote_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vote_pkey'))
    )
    op.create_index(op.f('ix_vote_id'), 'vote', ['id'], unique=False)
    op.create_table('clip',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('twitch_clip_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('creator_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('month_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clip_pkey')),
    sa.UniqueConstraint('twitch_clip_id', name=op.f('clip_twitch_clip_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_clip_month_key'), 'clip', ['month_key'], unique=False)
    op.create_index(op.f('ix_clip_id'), 'clip', ['id'], unique=False)
    op.create_table('user_streamer',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('streamer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('twitch_channel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_streamer_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_streamer_pkey'))
    )
    op.create_index(op.f('ix_user_streamer_id'), 'user_streamer', ['id'], unique=False)
    op.drop_index(op.f('ix_clip_video_cache_id'), table_name='clip_video_cache')
    op.drop_index(op.f('ix_clip_video_cache_clip_id'), table_name='clip_video_cache')
    op.drop_table('clip_video_cache')
    op.drop_index('ix_leaderboard_snapshots_timestamp', table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_snapshot_timestamp'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_snapshot_month'), table_name='leaderboard_snapshots')
    op.drop_index('ix_leaderboard_snapshots_month', table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_id'), table_name='leaderboard_snapshots')
    op.drop_table('leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_monthly_summary_snapshot_month'), table_name='leaderboard_monthly_summary')
    op.drop_index('ix_leaderboard_monthly_summary_month', table_name='leaderboard_monthly_summary')
    op.drop_index(op.f('ix_leaderboard_monthly_summary_id'), table_name='leaderboard_monthly_summary')
    op.drop_table('leaderboard_monthly_summary')
    # ### end Alembic commands ###
